/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movie_hub;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author asakt
 */
public class InsertForm2 extends javax.swing.JFrame {

    /**
     * Creates new form InsertForm2
     */
    public InsertForm2() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public InsertForm2(int i){
        //System.out.println(i);
        ind=i;
        roleList=getRoleList(i);
        //System.out.println(Arrays.toString(roleList));
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose Role");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        jLabel1.setText("Select the role:");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(roleList));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nextButton.setBackground(new java.awt.Color(204, 204, 0));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        Movie_hub.roleIdI=((String) roleComboBox.getSelectedItem()).substring(0,5);
        try {
            new InsertForm3(ind).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(InsertForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new InsertForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertForm2().setVisible(true);
            }
        });
    }
    
    @SuppressWarnings("empty-statement")
    private String[] getRoleList(int i) {
    String[] roles = null;
    switch (i) {
        case 0:
            roles = new String[]{"RP001 - Andy Dufresne", "RP002 - Ellis Boyd 'Red' Redding", "RP003 - Warden Norton"};
            break;
        case 1:
            roles = new String[]{"RP004 - Vito Corleone", "RP005 - Michael Corleone", "RP006 - Sonny Corleone"};
            break;
        case 2:
            roles = new String[]{"RP007 - Bruce Wayne", "RP008 - Joker", "RP009 - Harvey Dent"};
            break;
        case 3:
            roles = new String[]{"RP010 - Michael Corleone", "RP011 - Young Vito Corleone", "RP012 - Tom Hagen"};
            break;
        case 4:
            roles = new String[]{"RP013 - Juror 1", "RP014 - Juror 2", "RP015 - Juror 3"};
            break;
        case 5:
            roles = new String[]{"RP016 - Oskar Schindler", "RP017 - Itzhak Stern", "RP018 - Amon Goeth"};
            break;
        case 6:
            roles = new String[]{"RP019 - Frodo Baggins", "RP020 - Aragorn", "RP021 - Gandalf"};
            break;
        case 7:
            roles = new String[]{"RP022 - Vincent Vega", "RP023 - Mia Wallace", "RP024 - Jules Winnfield"};
            break;
        case 8:
            roles = new String[]{"RP019 - Frodo Baggins", "RP021 - Gandalf", "RP027 - Legolas"};
            break;
        case 9:
            roles = new String[]{"RP028 - Tyler Durden", "RP029 - Narrator", "RP030 - Marla Singer"};
            break;
        case 10:
            roles = new String[]{"RP031 - Forrest Gump", "RP032 - Jenny Curran", "RP033 - Lt. Dan Taylor"};
            break;
        case 11:
            roles = new String[]{"RP034 - Cobb", "RP035 - Arthur", "RP036 - Ariadne"};
            break;
        case 12:
            roles = new String[]{"RP037 - Neo", "RP038 - Morpheus", "RP039 - Trinity"};
            break;
        case 13:
            roles = new String[]{"RP019 - Frodo Baggins", "RP021 - Gandalf", "RP040 - Aragorn"};
            break;
        case 14:
            roles = new String[]{"RP043 - James 'Jimmy' Conway", "RP044 - Henry Hill", "RP045 - Tommy DeVito"};
            break;
        case 15:
            roles = new String[]{"RP046 - Clarice Starling", "RP047 - Dr. Hannibal Lecter", "RP048 - Jack Crawford"};
            break;
        case 16:
            roles = new String[]{"RP049 - Luke Skywalker", "RP050 - Han Solo", "RP051 - Princess Leia"};
            break;
        case 17:
            roles = new String[]{"RP052 - Paul Edgecomb", "RP053 - John Coffey", "RP054 - Brutus 'Brutal' Howell"};
            break;
        case 18:
            roles = new String[]{"RP055 - Philippe", "RP056 - Driss", "RP057 - Yvonne"};
            break;
        case 19:
            roles = new String[]{"RP058 - Robert Angier", "RP059 - Alfred Borden", "RP060 - Cutter"};
            break;
        case 20:
            roles = new String[]{"RP061 - Ramanujam Iyengar (Ambi)", "RP062 - Remo", "RP063 - Anniyan", "RP064 - Nandini", "RP065 - Chari", "RP066 - DCP Prabhakar"};
            break;
        case 21:
            roles = new String[]{"RP067 - Senapathy", "RP068 - Senapathy's Father", "RP069 - Thilakan"};
            break;
        case 22:
            roles = new String[]{"RP070 - Rangarajan Nambi", "RP071 - Govind Ramasaamy", "RP072 - Avatar Singh"};
            break;
        case 23:
            roles = new String[]{"RP073 - Raghava", "RP074 - Kanchana", "RP075 - Raghavan"};
            break;
        case 24:
            roles = new String[]{"RP076 - Vikram", "RP077 - Vedha", "RP078 - Chandra"};
            break;
        default:
            break;
    }
    return roles;
}


    private String[] roleList;
    private int ind=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox<String> roleComboBox;
    // End of variables declaration//GEN-END:variables
}
